/*
 * Looker API 4.0 (Experimental) Reference
 *
 *  Welcome to the future! This is an early preview of our next-generation Looker API 4.0. API 4.0 runs alongside APIs 3.1 and 3.0. We've tagged 4.0 as \"experimental\" to reflect that we have more work planned for API 4.0 which may include breaking changes. Please pardon our dust while we remodel a few rooms!  ### In This Release  We're spinning up this new API 4.0 version so that we can make adjustments to our API functions, parameters, and response types to fix bugs and inconsistencies. These changes fall outside the bounds of non-breaking additive changes we can make to our stable API 3.1.  One benefit of these type adjustments in API 4.0 is dramatically better support for strongly typed languages like TypeScript, Kotlin, Java, and more. Looker is also creating client SDKs to call the Looker API from these and other languages. These client SDKs will be available as pre-built packages for download from public repositories such as npmjs.org, RubyGems.org, PyPi.org. If you use an IDE for software development, you will soon be able to install a Looker SDK for your programming language with the click of a button!  While API 3.1 is still the defacto Looker API (\"current\", \"stable\", \"default\", etc), the bulk of our development activity will gradually shift to API 4.0.  
 *
 * API version: 4.0.7.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package looker
// DashboardBase struct for DashboardBase
type DashboardBase struct {
	// Operations the current user is able to perform on this object
	Can map[string]bool `json:"can,omitempty"`
	// Content Favorite Id
	ContentFavoriteId int64 `json:"content_favorite_id,omitempty"`
	// Id of content metadata
	ContentMetadataId int64 `json:"content_metadata_id,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	// Is Hidden
	Hidden bool `json:"hidden,omitempty"`
	// Unique Id
	Id string `json:"id,omitempty"`
	Model LookModel `json:"model,omitempty"`
	// Timezone in which the Dashboard will run by default.
	QueryTimezone string `json:"query_timezone,omitempty"`
	// Is Read-only
	Readonly bool `json:"readonly,omitempty"`
	// Refresh Interval, as a time duration phrase like \"2 hours 30 minutes\". A number with no time units will be interpreted as whole seconds.
	RefreshInterval string `json:"refresh_interval,omitempty"`
	// Refresh Interval in milliseconds
	RefreshIntervalToI int64 `json:"refresh_interval_to_i,omitempty"`
	Folder FolderBase `json:"folder,omitempty"`
	// Dashboard Title
	Title string `json:"title,omitempty"`
	// Id of User
	UserId int64 `json:"user_id,omitempty"`
}
