/*
 * Looker API 4.0 (Experimental) Reference
 *
 *  Welcome to the future! This is an early preview of our next-generation Looker API 4.0. API 4.0 runs alongside APIs 3.1 and 3.0. We've tagged 4.0 as \"experimental\" to reflect that we have more work planned for API 4.0 which may include breaking changes. Please pardon our dust while we remodel a few rooms!  ### In This Release  We're spinning up this new API 4.0 version so that we can make adjustments to our API functions, parameters, and response types to fix bugs and inconsistencies. These changes fall outside the bounds of non-breaking additive changes we can make to our stable API 3.1.  One benefit of these type adjustments in API 4.0 is dramatically better support for strongly typed languages like TypeScript, Kotlin, Java, and more. Looker is also creating client SDKs to call the Looker API from these and other languages. These client SDKs will be available as pre-built packages for download from public repositories such as npmjs.org, RubyGems.org, PyPi.org. If you use an IDE for software development, you will soon be able to install a Looker SDK for your programming language with the click of a button!  While API 3.1 is still the defacto Looker API (\"current\", \"stable\", \"default\", etc), the bulk of our development activity will gradually shift to API 4.0.  
 *
 * API version: 4.0.7.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package looker
import (
	"time"
)
// OauthClientApp struct for OauthClientApp
type OauthClientApp struct {
	// Operations the current user is able to perform on this object
	Can map[string]bool `json:"can,omitempty"`
	// The globally unique id of this application
	ClientGuid string `json:"client_guid,omitempty"`
	// The uri with which this application will receive an auth code by browser redirect.
	RedirectUri string `json:"redirect_uri,omitempty"`
	// The application's display name
	DisplayName string `json:"display_name,omitempty"`
	// A description of the application that will be displayed to users
	Description string `json:"description,omitempty"`
	// When enabled is true, OAuth2 and API requests will be accepted from this app. When false, all requests from this app will be refused.
	Enabled bool `json:"enabled,omitempty"`
	// If set, only Looker users who are members of this group can use this web app with Looker. If group_id is not set, any Looker user may use this app to access this Looker instance
	GroupId int64 `json:"group_id,omitempty"`
	// All auth codes, access tokens, and refresh tokens issued for this application prior to this date-time for ALL USERS will be invalid.
	TokensInvalidBefore time.Time `json:"tokens_invalid_before,omitempty"`
	// All users who have been activated to use this app
	ActivatedUsers []UserPublic `json:"activated_users,omitempty"`
}
