/*
 * Looker API 4.0 (Experimental) Reference
 *
 *  Welcome to the future! This is an early preview of our next-generation Looker API 4.0. API 4.0 runs alongside APIs 3.1 and 3.0. We've tagged 4.0 as \"experimental\" to reflect that we have more work planned for API 4.0 which may include breaking changes. Please pardon our dust while we remodel a few rooms!  ### In This Release  We're spinning up this new API 4.0 version so that we can make adjustments to our API functions, parameters, and response types to fix bugs and inconsistencies. These changes fall outside the bounds of non-breaking additive changes we can make to our stable API 3.1.  One benefit of these type adjustments in API 4.0 is dramatically better support for strongly typed languages like TypeScript, Kotlin, Java, and more. Looker is also creating client SDKs to call the Looker API from these and other languages. These client SDKs will be available as pre-built packages for download from public repositories such as npmjs.org, RubyGems.org, PyPi.org. If you use an IDE for software development, you will soon be able to install a Looker SDK for your programming language with the click of a button!  While API 3.1 is still the defacto Looker API (\"current\", \"stable\", \"default\", etc), the bulk of our development activity will gradually shift to API 4.0.  
 *
 * API version: 4.0.7.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package looker
// SshTunnel struct for SshTunnel
type SshTunnel struct {
	// Unique ID for the tunnel
	TunnelId string `json:"tunnel_id,omitempty"`
	// SSH Server ID
	SshServerId string `json:"ssh_server_id,omitempty"`
	// SSH Server name
	SshServerName string `json:"ssh_server_name,omitempty"`
	// SSH Server Hostname or IP Address
	SshServerHost string `json:"ssh_server_host,omitempty"`
	// SSH Server port
	SshServerPort int64 `json:"ssh_server_port,omitempty"`
	// Username used to connect to the SSH Server
	SshServerUser string `json:"ssh_server_user,omitempty"`
	// Time of last connect attempt
	LastAttempt string `json:"last_attempt,omitempty"`
	// Localhost Port used by the Looker instance to connect to the remote DB
	LocalHostPort int64 `json:"local_host_port,omitempty"`
	// Hostname or IP Address of the Database Server
	DatabaseHost string `json:"database_host,omitempty"`
	// Port that the Database Server is listening on
	DatabasePort int64 `json:"database_port,omitempty"`
	// Current connection status for this Tunnel
	Status string `json:"status,omitempty"`
}
