/*
 * Looker API 4.0 (Experimental) Reference
 *
 *  Welcome to the future! This is an early preview of our next-generation Looker API 4.0. API 4.0 runs alongside APIs 3.1 and 3.0. We've tagged 4.0 as \"experimental\" to reflect that we have more work planned for API 4.0 which may include breaking changes. Please pardon our dust while we remodel a few rooms!  ### In This Release  We're spinning up this new API 4.0 version so that we can make adjustments to our API functions, parameters, and response types to fix bugs and inconsistencies. These changes fall outside the bounds of non-breaking additive changes we can make to our stable API 3.1.  One benefit of these type adjustments in API 4.0 is dramatically better support for strongly typed languages like TypeScript, Kotlin, Java, and more. Looker is also creating client SDKs to call the Looker API from these and other languages. These client SDKs will be available as pre-built packages for download from public repositories such as npmjs.org, RubyGems.org, PyPi.org. If you use an IDE for software development, you will soon be able to install a Looker SDK for your programming language with the click of a button!  While API 3.1 is still the defacto Looker API (\"current\", \"stable\", \"default\", etc), the bulk of our development activity will gradually shift to API 4.0.  
 *
 * API version: 4.0.7.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package looker
import (
	"time"
)
// UserLoginLockout struct for UserLoginLockout
type UserLoginLockout struct {
	// Operations the current user is able to perform on this object
	Can map[string]bool `json:"can,omitempty"`
	// Hash of user's client id
	Key string `json:"key,omitempty"`
	// Authentication method for login failures
	AuthType string `json:"auth_type,omitempty"`
	// IP address of most recent failed attempt
	Ip string `json:"ip,omitempty"`
	// User ID
	UserId int64 `json:"user_id,omitempty"`
	// Remote ID of user if using LDAP
	RemoteId string `json:"remote_id,omitempty"`
	// User's name
	FullName string `json:"full_name,omitempty"`
	// Email address associated with the user's account
	Email string `json:"email,omitempty"`
	// Number of failures that triggered the lockout
	FailCount int64 `json:"fail_count,omitempty"`
	// Time when lockout was triggered
	LockoutAt time.Time `json:"lockout_at,omitempty"`
}
