/*
 * Looker API 4.0 (Experimental) Reference
 *
 *  Welcome to the future! This is an early preview of our next-generation Looker API 4.0. API 4.0 runs alongside APIs 3.1 and 3.0. We've tagged 4.0 as \"experimental\" to reflect that we have more work planned for API 4.0 which may include breaking changes. Please pardon our dust while we remodel a few rooms!  ### In This Release  We're spinning up this new API 4.0 version so that we can make adjustments to our API functions, parameters, and response types to fix bugs and inconsistencies. These changes fall outside the bounds of non-breaking additive changes we can make to our stable API 3.1.  One benefit of these type adjustments in API 4.0 is dramatically better support for strongly typed languages like TypeScript, Kotlin, Java, and more. Looker is also creating client SDKs to call the Looker API from these and other languages. These client SDKs will be available as pre-built packages for download from public repositories such as npmjs.org, RubyGems.org, PyPi.org. If you use an IDE for software development, you will soon be able to install a Looker SDK for your programming language with the click of a button!  While API 3.1 is still the defacto Looker API (\"current\", \"stable\", \"default\", etc), the bulk of our development activity will gradually shift to API 4.0.  
 *
 * API version: 4.0.7.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package looker
// LookmlModelExplore struct for LookmlModelExplore
type LookmlModelExplore struct {
	// Fully qualified explore name (model name plus explore name)
	Id string `json:"id,omitempty"`
	// Explore name
	Name string `json:"name,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	// Label
	Label string `json:"label,omitempty"`
	// Explore title
	Title string `json:"title,omitempty"`
	// Scopes
	Scopes []string `json:"scopes,omitempty"`
	// Can Total
	CanTotal bool `json:"can_total,omitempty"`
	// Can Develop LookML
	CanDevelop bool `json:"can_develop,omitempty"`
	// Can See LookML
	CanSeeLookml bool `json:"can_see_lookml,omitempty"`
	// A URL linking to the definition of this explore in the LookML IDE.
	LookmlLink string `json:"lookml_link,omitempty"`
	// Can Save
	CanSave bool `json:"can_save,omitempty"`
	// Can Explain
	CanExplain bool `json:"can_explain,omitempty"`
	// Can pivot in the DB
	CanPivotInDb bool `json:"can_pivot_in_db,omitempty"`
	// Can use subtotals
	CanSubtotal bool `json:"can_subtotal,omitempty"`
	// Has timezone support
	HasTimezoneSupport bool `json:"has_timezone_support,omitempty"`
	// Cost estimates supported
	SupportsCostEstimate bool `json:"supports_cost_estimate,omitempty"`
	// Connection name
	ConnectionName string `json:"connection_name,omitempty"`
	// How nulls are sorted, possible values are \"low\", \"high\", \"first\" and \"last\"
	NullSortTreatment string `json:"null_sort_treatment,omitempty"`
	// List of model source files
	Files []string `json:"files,omitempty"`
	// Primary source_file file
	SourceFile string `json:"source_file,omitempty"`
	// Name of project
	ProjectName string `json:"project_name,omitempty"`
	// Name of model
	ModelName string `json:"model_name,omitempty"`
	// Name of view
	ViewName string `json:"view_name,omitempty"`
	// Is hidden
	Hidden bool `json:"hidden,omitempty"`
	// A sql_table_name expression that defines what sql table the view/explore maps onto. Example: \"prod_orders2 AS orders\" in a view named orders.
	SqlTableName string `json:"sql_table_name,omitempty"`
	// (DEPRECATED) Array of access filter field names
	AccessFilterFields []string `json:"access_filter_fields,omitempty"`
	// Access filters
	AccessFilters []LookmlModelExploreAccessFilter `json:"access_filters,omitempty"`
	// Aliases
	Aliases []LookmlModelExploreAlias `json:"aliases,omitempty"`
	// Always filter
	AlwaysFilter []LookmlModelExploreAlwaysFilter `json:"always_filter,omitempty"`
	// Conditionally filter
	ConditionallyFilter []LookmlModelExploreConditionallyFilter `json:"conditionally_filter,omitempty"`
	// Array of index fields
	IndexFields []string `json:"index_fields,omitempty"`
	// Sets
	Sets []LookmlModelExploreSet `json:"sets,omitempty"`
	// An array of arbitrary string tags provided in the model for this explore.
	Tags []string `json:"tags,omitempty"`
	// Errors
	Errors []LookmlModelExploreError `json:"errors,omitempty"`
	Fields LookmlModelExploreFieldset `json:"fields,omitempty"`
	// Views joined into this explore
	Joins []LookmlModelExploreJoins `json:"joins,omitempty"`
	// Label used to group explores in the navigation menus
	GroupLabel string `json:"group_label,omitempty"`
	// An array of items describing which custom measure types are supported for creating a custom measure 'based_on' each possible dimension type.
	SupportedMeasureTypes []LookmlModelExploreSupportedMeasureType `json:"supported_measure_types,omitempty"`
}
