/*
 * Looker API 4.0 (Experimental) Reference
 *
 *  Welcome to the future! This is an early preview of our next-generation Looker API 4.0. API 4.0 runs alongside APIs 3.1 and 3.0. We've tagged 4.0 as \"experimental\" to reflect that we have more work planned for API 4.0 which may include breaking changes. Please pardon our dust while we remodel a few rooms!  ### In This Release  We're spinning up this new API 4.0 version so that we can make adjustments to our API functions, parameters, and response types to fix bugs and inconsistencies. These changes fall outside the bounds of non-breaking additive changes we can make to our stable API 3.1.  One benefit of these type adjustments in API 4.0 is dramatically better support for strongly typed languages like TypeScript, Kotlin, Java, and more. Looker is also creating client SDKs to call the Looker API from these and other languages. These client SDKs will be available as pre-built packages for download from public repositories such as npmjs.org, RubyGems.org, PyPi.org. If you use an IDE for software development, you will soon be able to install a Looker SDK for your programming language with the click of a button!  While API 3.1 is still the defacto Looker API (\"current\", \"stable\", \"default\", etc), the bulk of our development activity will gradually shift to API 4.0.  
 *
 * API version: 4.0.7.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package looker
// ThemeSettings struct for ThemeSettings
type ThemeSettings struct {
	// Default background color
	BackgroundColor string `json:"background_color,omitempty"`
	// Base font size for scaling fonts
	BaseFontSize string `json:"base_font_size,omitempty"`
	// Optional. ID of color collection to use with the theme. Use an empty string for none.
	ColorCollectionId string `json:"color_collection_id,omitempty"`
	// Default font color
	FontColor string `json:"font_color,omitempty"`
	// Primary font family
	FontFamily string `json:"font_family,omitempty"`
	// Source specification for font
	FontSource string `json:"font_source,omitempty"`
	// Info button color
	InfoButtonColor string `json:"info_button_color,omitempty"`
	// Primary button color
	PrimaryButtonColor string `json:"primary_button_color,omitempty"`
	// Toggle to show filters. Defaults to true.
	ShowFiltersBar bool `json:"show_filters_bar,omitempty"`
	// Toggle to show the title. Defaults to true.
	ShowTitle bool `json:"show_title,omitempty"`
	// Text color for text tiles
	TextTileTextColor string `json:"text_tile_text_color,omitempty"`
	// Background color for tiles
	TileBackgroundColor string `json:"tile_background_color,omitempty"`
	// Text color for tiles
	TileTextColor string `json:"tile_text_color,omitempty"`
	// Color for titles
	TitleColor string `json:"title_color,omitempty"`
	// Warning button color
	WarnButtonColor string `json:"warn_button_color,omitempty"`
	// The text alignment of tile titles (New Dashboards)
	TileTitleAlignment string `json:"tile_title_alignment,omitempty"`
	// Toggles the tile shadow (New Dashboards)
	TileShadow bool `json:"tile_shadow,omitempty"`
}
